### ISSUE TITLE
Enternity - Abyssea Golden Chests

### ISSUE THREAD

**Issue by BlackrosesXI** [giulianoriccio/Lua#27] opened 2013-06-23 23:40 UTC
When using Enternity, it is currently impossible to see the exact stats on an item in a golden chest (ex: Tarutaru sash in abyseas latheine).

**Comment by giulianoriccio** [comment] 2013-06-28 09:32
Duplicate of #25 
Continuing the discussion there.

**Closed as completed by giulianoriccio** 2013-06-28 09:32 UTC
Labels: bug, duplicate, enternity
